---

- name: Install Slurm DB packages
  package:
    name: "{{ __slurm_packages.slurmdbd }}"
    state: "{{ 'latest' if slurm_upgrade else 'present' }}"

- name: Install slurmdbd.conf
  template:
    src: generic.conf.j2
    dest: "{{ slurm_config_dir }}/slurmdbd.conf"
    owner: "{{ __slurm_user_name }}"
    group: root
    mode: 0400
  notify:
    - reload slurmdbd

- name: Create slurm log directory
  file:
    path: "{{ __slurmdbd_config_merged.LogFile | dirname }}"
    owner: "{{ __slurm_user_name }}"
    group: "{{ __slurm_group_name }}"
    mode: 0755
    state: directory
  when: slurm_create_dirs and __slurmdbd_config_merged.LogFile

- name: Check for existence of cluster in db.
  register: cluster_check
  shell: "sacctmgr -n list cluster | cut -f 4 -d ' '"
  become: yes
  become_user: root

- name: set cluster_check_boolean
  set_fact:
      __cluster_not_setup: false
  when: cluster_check.stdout == "cluster"

- name: Create the slurmdbd cluster
  command: sacctmgr -i -n add cluster {{ __slurm_cluster_name }}
  become: yes
  become_user: root
  notify:
    - reload slurmdbd
  when: __cluster_not_setup
