---

- name: Create slurm group
  group:
    name: "{{ slurm_user.name | default('slurm') }}"
    gid: "{{ slurm_user.gid | default(omit) }}"
    system: "{{ slurm_user.system | default('yes') }}"

- name: Create slurm user
  user:
    name: "{{ slurm_user.name | default('slurm') }}"
    comment: "{{ slurm_user.comment | default(omit) }}"
    uid: "{{ slurm_user.uid | default(omit) }}"
    group: "{{ slurm_user.group | default(slurm_user.name | default('slurm')) }}"
    groups: "{{ slurm_user.groups | default(omit) }}"
    home: "{{ slurm_user.home | default(omit) }}"
    shell: "{{ slurm_user.shell | default(omit) }}"
    system: "{{ slurm_user.system | default('yes') }}"
